### ISSUE TITLE
Turn off text justification in tables

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#302] opened 2017-03-01 13:48 UTC
Tables tend to look horrible if there are even just multiple longish words in them. E.g. see the modules table in the SLES 12 SP2 RN (PDF version).

Not sure whether this applies for HTML as well...

**Comment by sknorr** [comment] 2017-09-20 16:09
ajajaj. I think you're right. (I looked at the Deployment Guide on docserv, so this has been fixed in 2.0.7.2 or before. Hence, I removed the misleading milestone here.)

**Comment by sknorr** [comment] 2017-10-23 18:31
Ok, looked at this again: The issue is fixed for entry/para/text() but it is not fixed if we have entry/text().
-> Reopening.

**Comment by janajaeger** [comment] 2022-07-20 08:41
@tomschr please advise on how to proceed. It doesn't look much of an issue in 2022 for me, though.

**Comment by tomschr** [comment] 2022-11-14 09:54
Tested with `entry/para/text()` and `entry/text()` in suse2022 stylesheets. Both look good. Already fixed.

**Closed by tomschr** 2022-11-14 09:54 UTC
Labels: cat-enhancement, format-pdf, styles-2022
