### ISSUE TITLE
Make Bugzilla integration localizable

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#117] opened 2015-12-09 14:38 UTC
Using DocManager, you can add "Report Bug" links to the HTML version. However, these links are currently not localizable. Would be nice to have the string "Report Bug" in gentext.xsl somewhere, so we can use it.

**Comment by tomschr** [comment] 2022-07-04 08:50
This is something for @jfaltenbacher and Padraig. Could we send this to our translators too?

**Comment by tomschr** [comment] 2022-07-04 15:59
Forget it, it's a duplicate of #455, therefore closing.

**Closed by tomschr** 2022-07-04 15:59 UTC
Labels: cat-bug, format-html, topic-l10n, styles-2013, styles-2022, prio:high
