### ISSUE TITLE
small tgroup cols attribute v/ large colspec

### ISSUE THREAD

**Issue by sknorr** [openSUSE/suse-xsl#210] opened 2016-01-20 13:48 UTC
In a table, when the tgroup's cols attribute defines a smaller number of columns than the colspec elements, it would be great if the stylesheets did not trip.

We should probably just believe the colspec element, since these are the more visible than a single digit in a single attribute. A warning would be a good idea too.

**Comment by tomschr** [comment] 2018-09-20 20:54
Duplicate of #222

**Closed by tomschr** 2018-09-20 20:54 UTC
Labels: duplicate, enhancement, upstream
