### ISSUE TITLE
missing l10n templates

### ISSUE THREAD

**Issue by ghost** [openSUSE/suse-xsl#294] opened 2017-01-13 17:07 UTC
- [x] No template for "itemizedlist-label" (or any of its leaves) exists in the context named "styles" in the "zh_tw" localization.
- [x] object.xref.markup: empty xref template for linkend="app.naming" and @xrefstyle="select:number" (all langs, SLEHA Guide)

**Comment by janajaeger** [comment] 2022-07-20 07:07
@tomschr still an issue in 2022?

**Comment by tomschr** [comment] 2022-11-14 09:37
First item is already fixed. Second is a duplicate of #202

**Closed by tomschr** 2022-11-14 09:37 UTC
Labels: cat-bug, topic-l10n
